//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace localClient.SerRef {
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Client", Namespace = "http://schemas.datacontract.org/2004/07/WCFChatApp")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NadimakField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsrNameField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_C {
            get {
                return this.Id_CField;
            }
            set {
                if ((this.Id_CField.Equals(value) != true)) {
                    this.Id_CField = value;
                    this.RaisePropertyChanged("Id_C");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nadimak {
            get {
                return this.NadimakField;
            }
            set {
                if ((object.ReferenceEquals(this.NadimakField, value) != true)) {
                    this.NadimakField = value;
                    this.RaisePropertyChanged("Nadimak");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsrName {
            get {
                return this.UsrNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsrNameField, value) != true)) {
                    this.UsrNameField = value;
                    this.RaisePropertyChanged("UsrName");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Message", Namespace = "http://schemas.datacontract.org/2004/07/WCFChatApp")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_MsgField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_PosField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_PrimField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MsgTimeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgTxtField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Msg {
            get {
                return this.Id_MsgField;
            }
            set {
                if ((this.Id_MsgField.Equals(value) != true)) {
                    this.Id_MsgField = value;
                    this.RaisePropertyChanged("Id_Msg");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Pos {
            get {
                return this.Id_PosField;
            }
            set {
                if ((this.Id_PosField.Equals(value) != true)) {
                    this.Id_PosField = value;
                    this.RaisePropertyChanged("Id_Pos");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Prim {
            get {
                return this.Id_PrimField;
            }
            set {
                if ((this.Id_PrimField.Equals(value) != true)) {
                    this.Id_PrimField = value;
                    this.RaisePropertyChanged("Id_Prim");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MsgTime {
            get {
                return this.MsgTimeField;
            }
            set {
                if ((this.MsgTimeField.Equals(value) != true)) {
                    this.MsgTimeField = value;
                    this.RaisePropertyChanged("MsgTime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgTxt {
            get {
                return this.MsgTxtField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgTxtField, value) != true)) {
                    this.MsgTxtField = value;
                    this.RaisePropertyChanged("MsgTxt");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Group", Namespace = "http://schemas.datacontract.org/2004/07/WCFChatApp")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_GField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxMembersField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GName {
            get {
                return this.GNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GNameField, value) != true)) {
                    this.GNameField = value;
                    this.RaisePropertyChanged("GName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_G {
            get {
                return this.Id_GField;
            }
            set {
                if ((this.Id_GField.Equals(value) != true)) {
                    this.Id_GField = value;
                    this.RaisePropertyChanged("Id_G");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxMembers {
            get {
                return this.MaxMembersField;
            }
            set {
                if ((this.MaxMembersField.Equals(value) != true)) {
                    this.MaxMembersField = value;
                    this.RaisePropertyChanged("MaxMembers");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GroupClient", Namespace = "http://schemas.datacontract.org/2004/07/WCFChatApp")]
    [System.SerializableAttribute()]
    public partial class GroupClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_GField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_C
        {
            get
            {
                return this.Id_CField;
            }
            set
            {
                if ((this.Id_CField.Equals(value) != true))
                {
                    this.Id_CField = value;
                    this.RaisePropertyChanged("Id_C");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_G
        {
            get
            {
                return this.Id_GField;
            }
            set
            {
                if ((this.Id_GField.Equals(value) != true))
                {
                    this.Id_GField = value;
                    this.RaisePropertyChanged("Id_G");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerRef.IClient", CallbackContract=typeof(localClient.SerRef.IClientCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/LogIn", ReplyAction="http://tempuri.org/IClient/LogInResponse")]
        localClient.SerRef.Client LogIn(string UsrName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/LogIn", ReplyAction="http://tempuri.org/IClient/LogInResponse")]
        System.Threading.Tasks.Task<localClient.SerRef.Client> LogInAsync(string UsrName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IClient/LogOut")]
        void LogOut(localClient.SerRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IClient/LogOut")]
        System.Threading.Tasks.Task LogOutAsync(localClient.SerRef.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClient/sendMessage")]
        void sendMessage(localClient.SerRef.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClient/sendMessage")]
        System.Threading.Tasks.Task sendMessageAsync(localClient.SerRef.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClient/GroupRequest")]
        void GroupRequest(localClient.SerRef.Client c, localClient.SerRef.Group g);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClient/GroupRequest")]
        System.Threading.Tasks.Task GroupRequestAsync(localClient.SerRef.Client c, localClient.SerRef.Group g);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClient/GroupLeave")]
        void GroupLeave(localClient.SerRef.Client c, localClient.SerRef.Group g);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IClient/GroupLeave")]
        System.Threading.Tasks.Task GroupLeaveAsync(localClient.SerRef.Client c, localClient.SerRef.Group g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetGs", ReplyAction="http://tempuri.org/IClient/GetGsResponse")]
        System.Collections.Generic.List<localClient.SerRef.Group> GetGs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetGs", ReplyAction="http://tempuri.org/IClient/GetGsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<localClient.SerRef.Group>> GetGsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetMyClients", ReplyAction="http://tempuri.org/IClient/GetMyClientsResponse")]
        System.Collections.Generic.List<localClient.SerRef.Client> GetMyClients(int idC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetMyClients", ReplyAction="http://tempuri.org/IClient/GetMyClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<localClient.SerRef.Client>> GetMyClientsAsync(int idC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetMs", ReplyAction="http://tempuri.org/IClient/GetMsResponse")]
        void GetMs(System.Collections.Generic.List<localClient.SerRef.Message> msgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientChannel : localClient.SerRef.IClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientClient : System.ServiceModel.DuplexClientBase<localClient.SerRef.IClient>, localClient.SerRef.IClient {
        
        public ClientClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ClientClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ClientClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public localClient.SerRef.Client LogIn(string UsrName, string Password) {
            return base.Channel.LogIn(UsrName, Password);
        }
        
        public System.Threading.Tasks.Task<localClient.SerRef.Client> LogInAsync(string UsrName, string Password) {
            return base.Channel.LogInAsync(UsrName, Password);
        }
        
        public void LogOut(localClient.SerRef.Client client) {
            base.Channel.LogOut(client);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(localClient.SerRef.Client client) {
            return base.Channel.LogOutAsync(client);
        }
        
        public void sendMessage(localClient.SerRef.Message msg) {
            base.Channel.sendMessage(msg);
        }
        
        public System.Threading.Tasks.Task sendMessageAsync(localClient.SerRef.Message msg) {
            return base.Channel.sendMessageAsync(msg);
        }
        
        public void GroupRequest(localClient.SerRef.Client c, localClient.SerRef.Group g) {
            base.Channel.GroupRequest(c, g);
        }
        
        public System.Threading.Tasks.Task GroupRequestAsync(localClient.SerRef.Client c, localClient.SerRef.Group g) {
            return base.Channel.GroupRequestAsync(c, g);
        }
        
        public void GroupLeave(localClient.SerRef.Client c, localClient.SerRef.Group g) {
            base.Channel.GroupLeave(c, g);
        }
        
        public System.Threading.Tasks.Task GroupLeaveAsync(localClient.SerRef.Client c, localClient.SerRef.Group g) {
            return base.Channel.GroupLeaveAsync(c, g);
        }
        
        public System.Collections.Generic.List<localClient.SerRef.Group> GetGs() {
            return base.Channel.GetGs();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<localClient.SerRef.Group>> GetGsAsync() {
            return base.Channel.GetGsAsync();
        }
        
        public System.Collections.Generic.List<localClient.SerRef.Client> GetMyClients(int idC) {
            return base.Channel.GetMyClients(idC);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<localClient.SerRef.Client>> GetMyClientsAsync(int idC) {
            return base.Channel.GetMyClientsAsync(idC);
        }
    }
}
